#!/usr/bin/php
<?php

// Load Twig
require_once rtrim(__DIR__, '/').'/lib/Twig/lib/Twig/Autoloader.php';
Twig_Autoloader::register();

// Load our custom loader, this has to come after Twig because we're extending
// a base Twig class.
require_once 'FleetingFilesystem.php';

// Set our base directory
$basedir = rtrim(realpath(array_pop($argv)), '/').'/';

// Get the variables
$vars = array();
foreach ($argv as $arg) {
	if (preg_match('/--(\w+)=(.*)$/', $arg, $pair)) {
		$vars[$pair[1]] = $pair[2];
	}
}

// No base dir?! Error!
if (!is_dir($basedir)) {
	die("You must provide a base directory, not a filename.\n");
}
if (!$basedir) {
	die("Please set a base directory. Try `php twig /path/to/templates`.\n");
}

// Notify user
echo "Monitoring: {$basedir}\n";

// Build a list of files
function add_files($dir, &$files) {
	if ($handle = opendir($dir)) {
		while (false !== ($entry = readdir($handle))) {
			if (preg_match('/^\./', $entry)) {
				continue;
			}
		    else if (is_dir($dir.$entry)) {
		    	add_files($dir.$entry.'/', $files);
		    }
		    else if (preg_match('/^[^_].*\.twig$/', $entry)) {
		    	$files[$dir.$entry] = filemtime($dir.$entry);
		    }
		}

		closedir($handle);
	}
}

// Store the state of the files from the last loop
$last_files = array();

// Start watching… I'm so sorry for this…
while (true) {

	// Get the updated list of files
	$current_files = array();
	add_files($basedir, $current_files);

	// Compare our arrays and determine what has changed
	$modified = array_diff_assoc($current_files, $last_files);
	$deleted = array_diff_key($last_files, $current_files);

	// Re-render any updated or new files
	foreach ($modified as $file => $mtime) {
		
		// Load Twig
		$loader = new Twig_Loader_FleetingFilesystem($basedir);
		$twig = new Twig_Environment($loader);

		// Clear caches
		Twig_Template::clearCache();

		$relative_file = relative_file_name($file);
		$rendered_file = rendered_file_name($file);
		
		// Try our render
		try {
			$template = $twig->loadTemplate($relative_file);
			$rendered_contents = $template->render($vars);
			$flag = file_exists($rendered_file) ? 'U' : 'C';
			file_put_contents($rendered_file, $rendered_contents);
			echo "\033[32m{$flag} {$relative_file}\033[0m\n";
		}
		
		// Catch any errors
		catch (Exception $e) {
			echo "\033[31mE {$e->getRawMessage()} ({$e->getTemplateFile()}:{$e->getTemplateLine()})\033[0m\n";
		}
	}

	// Delete any old files
	foreach ($deleted as $file => $mtime) {
		$relative_file = relative_file_name($file);
		$rendered_file = rendered_file_name($file);
		@unlink($rendered_file);
		echo "D {$relative_file}\n";
	}

	// Do it all again
	$last_files = $current_files;

	// Release some memory
	unset($current_files);
	unset($modified);
	unset($deleted);
	unset($relative_file);
	unset($rendered_file);
	unset($rendered_contents);
	unset($flag);
	unset($e);

	// Pause to breathe
	sleep(1);
}

function relative_file_name($file) {
	global $basedir;
	return preg_replace('/^'.preg_quote($basedir, '/').'/', '', $file);
}

function rendered_file_name($file) {
	return preg_replace('/\.twig$/', '.html', $file);
}